### ISSUE TITLE
Could you include an OSS license for this theme?

### ISSUE THREAD

**Issue by daviwil** [bruce/emacs-spacegray-theme#7]
Hi @bruce!

First of all, thanks a lot for putting together this theme, it's my favorite for Emacs by far.  I know you haven't worked on it in a while, but I was wondering if it might be possible for you to include a LICENSE file for an OSS license, like GPL or MIT.  The reason why I ask is that I am working on packaging this theme for the [GNU Guix](https://guix.gnu.org) Linux distribution and specifying the license is an important part of defining the package.

Thanks in advance!

**Comment by daviwil** [comment]
Also, if you're interested in having some help maintaining this package, I'd be happy to!

**Comment by bruce** [comment]
@daviwil Yes to both! I’ll look at the license today.

**Comment by bruce** [comment]
@daviwil `LICENSE` file added.

**Comment by daviwil** [comment]
Thanks so much for adding the license!
